version: '3.4'

services:

  pos.report.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    ports:
      - "80"

  pos.product.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  pos.order.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  pos.customer.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development            
    ports:
      - "80"
  

  pos.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  pos.gateway.securities:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  pos.webapplication:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

